name: Deploy HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build Vue
        working-directory: client
        run: npm run build

      - name: Deploy to Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: Zhengyuuuui/vibe-diary-private
          huggingface_repo_id: realyuYU/Vibe-diary
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_type: space
          space_sdk: static
          local_dir: client/dist
