name: Deploy HuggingFace Space

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Build Vue
        working-directory: client
        run: npm run build

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd client/dist

          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Deploy to Hugging Face Space"

          git branch -M main
          git remote add origin https://Zhengyuuuui:${HF_TOKEN}@huggingface.co/spaces/realyuYU/Vibe-diary

          git push -f origin main
